### ISSUE TITLE
MQTT not functional, missing documentation

### ISSUE THREAD

**Issue by Dids** [goliothlabs/arduino-sdk#4]
When I first discovered this particular project, and how it seemed to simple to get it working with Golioth, I was very excited and got to work immediately.

However, it didn't take me long to realize that the secure MQTT connection does not, at least not according to the examples here, and since there's _zero_ documentation on this SDK (or Golioth's MQTT server) on the main Golioth website, I'm starting to suspect that this functionality has been abandoned since, and Golioth is only focusing on Zephyr, potentially even scrapping this project in its entirety eventually?

For more context, no matter which MQTT client I try to use, I'm unable to connect to Golioth's MQTT server using the example code/logic provided, eg. using PKS ID as username/device id + PKS as password + setting server/CA cert to Golioth/LE cert, I never get further than this:
```
[ 13925][E][ssl_client.cpp:132] start_ssl_client(): socket error on fd 48, errno: 104, "Connection reset by peer"
[ 13926][E][WiFiClientSecure.cpp:135] connect(): start_ssl_client: -1
```

I would highly appreciate if someone from Golioth could chime in on this, so we would know whether this route is still worth pursuing, or if we should give up and either migrate to Zephyr, or look for other options outside of Golioth.

**Comment by beriberikix** [comment]
Hi @Dids,

Apologies for the frustration this change may have caused. We've updated the readme to reflect the state of this experiment.

We have two official SDKs over on our main organization: our [Zephyr SDK](https://github.com/golioth/golioth-zephyr-sdk) and our [cross-platform SDK](https://github.com/golioth/golioth-firmware-sdk). Both are well-supported, tested, maintained and used in production.

For a bit of background, last year we experimented with different programming frameworks like Arduino & MicroPython and adding new protocols like MQTT, which we released as a Beta service. The feedback from the community and customers was that they preferred we focus on Zephyr and specific vendor-provided software stacks (like Espressif's ESP-IDF.) They also wanted more CoAP-focused features. Due to the small size of the team and very limited adoption of these experiments, we made the decision to end the experiments by ending the MQTT Beta. We tried reaching out to any users who were impacted by it but we seemed to have missed you. Sorry for that :/ Instead of simply deleting the experiments here in Golioth Labs we decided to keep them in case either the community was interested in them or if we decide to re-invest in the future. For example, folks the Ribbit Network project took our original MicroPython experiment and [made it work](https://github.com/Ribbit-Network/ribbit-network-frog-software) over CoAP for their sensor.
